#!/usr/bin/env python3
"""Regenerate _data/publications.yml from the InspireHEP API.

Run by .github/workflows/update-publications.yml on a schedule. This file
is machine-generated -- manual edits to _data/publications.yml will be
overwritten on the next run.
"""
import html
import json
import re
import urllib.request
from pathlib import Path

AUTHOR_RECORD_ID = "1890429"  # https://inspirehep.net/authors/1890429
CANONICAL_NAME = "G. Franco Abellán"
THESIS_URL = "https://theses.hal.science/tel-04217480v1"

# Manual overrides for the "journal" tag, keyed by arXiv ID, for entries
# where InspireHEP has no (or the wrong) journal/proceedings info -- e.g.
# conference proceedings that never get a journal_title from the API.
JOURNAL_OVERRIDES = {
    "2410.15808": {  # Mean-Field Simulation-Based Inference for Cosmological Initial Conditions
        "journal": "NeurIPS",
        "journal_url": "https://neurips.cc/virtual/2024/100110",
    },
}

# arXiv IDs whose full author list should always be shown, bypassing the
# >6-authors truncation below.
FULL_AUTHOR_LIST_OVERRIDES = {
    "2202.09379",  # Hints of early dark energy in Planck, SPT, and ACT data
}
API_URL = (
    "https://inspirehep.net/api/literature"
    "?sort=mostrecent&size=250&page=1"
    "&q=a%20guillermo.franco.abellan.1"
    "&fields=titles,arxiv_eprints,publication_info,earliest_date,dois,"
    "authors.full_name,authors.record,document_type,citation_count"
)
OUT_PATH = Path(__file__).resolve().parent.parent.parent / "_data" / "publications.yml"
STATS_PATH = Path(__file__).resolve().parent.parent.parent / "_data" / "stats.yml"

HEADER = """# Publications, newest first.
# AUTO-GENERATED by .github/workflows/update-publications.yml -- do not
# hand-edit, changes will be overwritten on the next scheduled run.
# Source: https://inspirehep.net/authors/{author_id}
""".format(author_id=AUTHOR_RECORD_ID)


def strip_tags(text):
    text = re.sub(r"<[^>]+>", "", text)
    text = html.unescape(text)
    text = text.replace("$", "")  # drop LaTeX math delimiters, e.g. $S_8$
    text = re.sub(r"_(\d+)", r"<sub>\1</sub>", text)  # S_8 -> S<sub>8</sub>
    # Some titles come from MathML rather than LaTeX (e.g. "H0 Olympics"),
    # which loses the subscript entirely once tags are stripped above.
    # Restore it for the two quantities that show up in our titles.
    text = re.sub(r"\bH0\b", "H<sub>0</sub>", text)
    text = re.sub(r"\bS8\b", "S<sub>8</sub>", text)
    return re.sub(r"\s+", " ", text).strip()


def format_author(author):
    ref = (author.get("record") or {}).get("$ref", "")
    if ref.rstrip("/").endswith(f"/authors/{AUTHOR_RECORD_ID}"):
        return CANONICAL_NAME
    full_name = author.get("full_name", "")
    if "," in full_name:
        last, first = full_name.split(",", 1)
    else:
        last, first = full_name, ""
    last = last.strip()
    first = first.strip()
    # Initial per given name, not just the first one -- handles middle
    # initials and cases where InspireHEP misfiles part of a compound
    # surname as a given name (e.g. "Herrera, Guadalupe Cañas" -> "G. C.").
    initials = " ".join(f"{w[0]}." for w in first.split() if w)
    return f"{initials} {last}".strip()


def yaml_str(value):
    return json.dumps(value, ensure_ascii=False)


JOURNAL_ABBREVIATIONS = {
    # InspireHEP's journal_title is sometimes an unusually long form, or
    # longer than we want on a small colored badge; prefer the short form.
    "Mon. Not. Roy. Astron. Soc.": "MNRAS",
    "Phys. Rev. D": "PRD",
}


def format_journal(name):
    # InspireHEP returns compact codes like "Phys.Rev.D"; space them out.
    name = re.sub(r"\.(?=[A-Za-z])", ". ", name)
    return JOURNAL_ABBREVIATIONS.get(name, name)


def compute_h_index(citation_counts):
    counts = sorted(citation_counts, reverse=True)
    h = 0
    for i, c in enumerate(counts, start=1):
        if c >= i:
            h = i
        else:
            break
    return h


def build_entry(hit):
    m = hit["metadata"]
    year = (m.get("earliest_date") or "")[:4]
    title = strip_tags(m.get("titles", [{}])[0].get("title", ""))
    authors = m.get("authors", [])
    formatted = [format_author(a) for a in authors]
    arxiv_list = m.get("arxiv_eprints") or []
    arxiv_id = arxiv_list[0].get("value", "") if arxiv_list else ""
    lines = [
        f"- year: {year}",
        f"  title: {yaml_str(title)}",
    ]
    if len(authors) > 6 and arxiv_id not in FULL_AUTHOR_LIST_OVERRIDES:
        shown = formatted[:3] + ["et al."]
        lines.append("  authors: [" + ", ".join(yaml_str(a) for a in shown) + "]")
        lines.append(f"  collab_note: \"{len(authors)} authors\"")
    else:
        lines.append("  authors: [" + ", ".join(yaml_str(a) for a in formatted) + "]")
    override = JOURNAL_OVERRIDES.get(arxiv_id)

    if override:
        lines.append(f"  journal: {yaml_str(override['journal'])}")
        lines.append(f"  journal_url: {yaml_str(override['journal_url'])}")
    else:
        pub_info = m.get("publication_info") or [{}]
        journal = pub_info[0].get("journal_title", "")
        if journal:
            lines.append(f"  journal: {yaml_str(format_journal(journal))}")
        dois = m.get("dois") or []
        if dois and dois[0].get("value"):
            lines.append(f"  doi: {yaml_str(dois[0]['value'])}")

    if arxiv_id:
        lines.append(f"  arxiv: {yaml_str(arxiv_id)}")
    categories = arxiv_list[0].get("categories") if arxiv_list else None
    if categories:
        lines.append("  categories: [" + ", ".join(yaml_str(c) for c in categories) + "]")
    citation_count = m.get("citation_count")
    if citation_count is not None:
        lines.append(f"  citations: {citation_count}")
    if "thesis" in (m.get("document_type") or []):
        lines.append("  note: \"PhD thesis\"")
        lines.append(f"  note_url: {yaml_str(THESIS_URL)}")
    return "\n".join(lines)


def main():
    with urllib.request.urlopen(API_URL, timeout=30) as resp:
        data = json.load(resp)

    hits = data.get("hits", {}).get("hits", [])
    hits.sort(key=lambda h: h["metadata"].get("earliest_date", ""), reverse=True)

    entries = [build_entry(h) for h in hits]
    content = HEADER + "\n" + "\n\n".join(entries) + "\n"
    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {len(entries)} publications to {OUT_PATH}")

    non_thesis_hits = [
        h for h in hits if "thesis" not in (h["metadata"].get("document_type") or [])
    ]
    citation_counts = [h["metadata"].get("citation_count") or 0 for h in non_thesis_hits]
    stats_content = (
        "# AUTO-GENERATED by .github/workflows/update-publications.yml -- do not\n"
        "# hand-edit, changes will be overwritten on the next scheduled run.\n"
        f"paper_count: {len(non_thesis_hits)}\n"
        f"h_index: {compute_h_index(citation_counts)}\n"
    )
    STATS_PATH.write_text(stats_content, encoding="utf-8")
    print(f"Wrote stats to {STATS_PATH}")


if __name__ == "__main__":
    main()
